### ISSUE TITLE
Cucumber Linux isn't supported

### ISSUE THREAD

**Issue by aastroplant** [dylanaraps/neofetch#1213]
## Description

Could you add [Cucumber Linux](https://cucumberlinux.com/)?

**Comment by dylanaraps** [comment]
Output of `cat /etc/os-release`, `lsb-release`, `lsb_release`. Also  what package manager does it use?

**Comment by jprfts** [comment]
Yeah, about that. I actually went out of my way to find an obscure af distro to submit, without realizing I would then have to download it, install it, and do the things in order to get it in neofetch.
So I thought "f*ck it" and flashed it on a USB drive. But it's in an early alpha and I can't get it to boot. Whether you decide to go through the trouble of adding it is up to you I guess.

**Comment by astro-plant** [comment]
/etc/os-release isn't a file that exists in my system, but /etc/lsb-release gives:

```
# Do NOT edit this file. It is generated automatically as part of the Cucumber
# Linux installation process.
DISTRIB_ID="Cucumber Linux"
DISTRIB_RELEASE="1.1"
DISTRIB_CODENAME="Luke"
DISTRIB_DESCRIPTION="Scott Court's Cucumber Linux Distribution"

# The following fields are not required as part of the LSB. They are here to
# provide supplemental information only.
DISTRIB_TYPE="stable"
DISTRIB_ROLLING_RELEASE="1.x"
DISTRIB_ARCH=i686
```

lsb_release is the same also.
