### ISSUE TITLE
Android Termux installation should be with pkg not apt

### ISSUE THREAD

**Issue by adriiii1** [dylanaraps/neofetch#1236]
## Description
Installation on termux has to be done with pkg install neofetch, not sudo apt-get update

**Comment by konimex** [comment]
Uh... What are you referring to?

Assuming you meant package detection, `apt` is (still) a valid command in Termux, but we detect `dpkg` directly instead of using `apt`. Ping @fornwall as I don't want to be mistaken.

**Comment by adriiii1** [comment]
I'm a bit dumb and wrote apt-get update instead of apt-get install neofetch, when you use apt-get in Termux it says that apt is not installed, but to use pkg, so the installation for neofetch on Termux is pkg install neofetch and the installation guide should be changed. I don't know if this is the place to say or if I should have just created a pull request.

**Comment by konimex** [comment]
>when you use apt-get in Termux it says that apt is not installed

I honestly don't know what you're talking about. `apt-get` exists in my Termux.

![Screenshot_20190503-095230_Termux](https://user-images.githubusercontent.com/15692230/57117867-668d6380-6d89-11e9-8a73-5ed0cb717615.png)

If you're talking about the installation instructions wiki, you can change it yourself.

Since this is not a neofetch issue, I'm closing it.
