### ISSUE TITLE
Calling all image issues

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#1392]
The image feature is a hack which doesn't work in all terminal emulators. To make matters worse it sometimes works in `example_terminal` on one machine but fails in `example_terminal` on another machine.

There is also the buggy and sometimes broken implementation of the "get terminal window size" escape sequence which can cause terminal size detection to fail on some systems.

I've been answering issues related to this for years and there's nothing I can do about resolving this issue. It's a hack! To ease the maintainence of this bug tracker, all image related issues will be directed here.

Please post your troubles, workarounds and overall discussion here.

**NOTE**: This doesn't include all image backends. Some work flawlessly as they convert the image to some form of textual representation. This also excludes backends like `kitty`, `sixel` and `iterm2` which have real support from terminal emulators.

**Comment by ShayBox** [comment]
afaik Uberzug works flawlessly on any X session, regardless of the terminal or desktop, so I believe it would be a good default and main focus as it would bring the most compatibility.

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/neofetch/issues/1172

I have no interest in Überzug and it is still the same hack I am talking about above, only it now loops instead of drawing once. As stated in the issue above; I will review patches which add this feature.

**Comment by linxed** [comment]
I've tried every possible config on the iterm2 but i still shows the apple logo, which log would you need me to provide you ?

**Comment by dylanaraps** [comment]
You need imagemagick installed.

**Comment by linxed** [comment]
very new to this, could you please tell me what i am doing wrong : 

```~/Downloads/ImageMagick-7.0.9-17
kristiyan make install
make: *** No rule to make target `install'.  Stop.
~/Downloads/ImageMagick-7.0.9-17
kristiyan```

**Comment by linxed** [comment]
Ok i got imagemagic installed now i get a broken image : 

```
kristiyan grep -i image neofetchlog | less -S
~
kristiyan grep -i image neofetchlog
+ image_backend
+ case ${image_backend:-off} in
+ get_image_source
+ case $image_source in
+ image=
+ err 'Image: Using image '\'''\'''
+ err+='[!]\e[0m Image: Using image '\'''\''
+ to_ascii 'Image: '\''auto'\'' doesn'\''t exist, falling back to ascii mode.'
+ err 'Image: '\''auto'\'' doesn'\''t exist, falling back to ascii mode.'
+ err+='[!]\e[0m Image: '\''auto'\'' doesn'\''t exist, falling back to ascii mode.
+ image_backend=ascii
[!]\e[0m Image: Using image '\'''\''
[!]\e[0m Image: '\''auto'\'' doesn'\''t exist, falling back to ascii mode.
[!] Image: Using image ''
[!] Image: 'auto' doesn't exist, falling back to ascii mode.
```

**Comment by dylanaraps** [comment]
Closing this issue and leaving it pinned.

**Comment by gardotd426** [comment]
This used to work perfectly in kitty with `--w3m`, hell it always worked in `gnome-terminal` with `--w3m` as well, but now it won't work in any terminal I've tested (alacritty, kitty, gnome-terminal, urxvt, xterm) with anything except for in kitty with the specific `--kitty` backend (even `neofetch --w3m <source> doesn't work in kitty anymore). Can't figure it out for the life of me.

**Comment by adrianrlaw** [comment]
This issue seems to be related to a hack implemented in `w3m-img` that would break in some terminals. As such, the patch has to be on w3m's end (though I think they're refusing to fix it). A rudimentary explanation is in [this mailing list](https://lists.suckless.org/dev/1304/15283.html) which refers to `st` specifically but should also apply to all other terminal emulators implementing the same or similar double buffering strategy.

**Comment by mattkelsey** [comment]
This might be useful for some people:
If you are using Wayland, then neofetch wont be able to detect your terminal size because there is not currently Wayland compatible tooling for fetching window size (i.e. `xdotool` only works with X and there is no equivalent for Wayland). Or if there is a tool, I haven't been able to find it.

If you have this issue, you'll get this error when running neofetch in verbose mode: `Image: Failed to find terminal window size.`

### Workaround
Run your terminal with XWayland (Wayland's X11 compatibility layer designed for apps that don't support Wayland). Just set the `GDK_BACKEND=x11` environment variable which will force the terminal to run under XWayland (for instance in Gnome you could modify your application file for your terminal to run with that env var prefaced). This allows all the X tooling to work as intended.

Of course this isn't good because your terminal can't run on Wayland but it's a small price to pay for sweet images! Also the terminal is not graphically demanding, so running through the compatibility layer doesn't seem like too big of an issue. Has been working fine for me so far.

**Comment by Malod219** [comment]
#1172 #1453 
@ShayBox @dylanaraps I wrote a patch to support Ueberzug.[https://pastebin.com/raw/y8wB4nEA](https://pastebin.com/raw/y8wB4nEA) I posted it on pastebin. It works on my machine which runs st. I believe it also meets most of the criteria for code convention, however I get 2 warnings from shellcheck that I'm unsure how to fix.
```In neofetch line 4167:
                        [identifier]="neofetch"\
                        ^----------^ SC2102: Ranges can only match single chars (mentioned due to duplicates).


In neofetch line 4170:
                        [max_height]="$((height / font_height))"\
                        ^----------^ SC2102: Ranges can only match single chars (mentioned due to duplicates).
```
Let me know if this patch works for you. It also depends on ueberzug.

**Comment by j-james** [comment]
The `--catimg` backend (from both `--catimg` and `--backend catimg` doesn't seem to be working on XFCE. The similar `--chafa` backend works fine. I've attached `-vv` logs below, but nothing really stood out in a diff - it looks like the `--catimg` backend thinks that it's `--ascii`.

```
teal@endeavour 
-------------- 
OS: EndeavourOS Linux x86_64 
Kernel: 5.8.12-arch1-1 
Shell: bash 5.0.18 
DE: Xfce 4.14 
WM: Xfwm4 
Terminal: xfce4-terminal 
Neofetch: 7.1.0 
```

https://gist.github.com/j-james/4c2500d379eaef25bacff6c3246a583f

**Comment by itxve** [comment]
#1605
here my config file
[config.txt](https://gist.github.com/itxve/b723a41c99508c72fc3903799f4862ec)
here my log file
[log.txt](https://gist.github.com/itxve/69d49f4345243241bac5825c62e4fd28)

**Comment by duaneking** [comment]
Please require that you have people submit not only the OS they are dealing with, but also if they are running inside docker or WSL or WSL2 or whatever.

None of the bug reports are useful in helping find the root cause for this because you are not collecting enough data in bug reports, and that sucks because my current theory is that this is a Win10 WSL issue but without the extra data I have no way to verify this.

WSL2 seems to be a big problem with support as no system I have been able to test will correctly report the terminal resolution and use an image correctly when using WLS, so neofetch always fails at the "Image: Failed to find terminal window size." stage and since the error also says to check the wiki, and the wiki does not even list the actual issue or why, or how to check, or how to debug, its really confusing and an absolutely horrible user experience. So of course they file a bug,

To fix this, update the wiki to include the terminal resolution issue, add a bash script people can use to check if they have the issue and call out WSL/WSL2 as a known possible issue based on the data available so far.

**Comment by madjoe** [comment]
Installing the following packages seems to help to fix this issue:

```
pacman -S xorg-xwininfo xorg-xdpyinfo xdotool
```

**Comment by JuanjoSalvador** [comment]
According to #1385, and as far I can test, `gnome-terminal` seems not supported anymore for displaying images. So maybe it should be removed from the wiki's compatibility list

**Comment by mattdm** [comment]
Reviewers and enthusiasts seem to really like neofetch for their screenshots.

So, I'd like for it to display the Fedora logo nicely. We're particularly interested because we're just about to launch a refresh of the logo, and we've identified neofetch as somewhere where we'd like this to work nicely. I'd _really_ like this to work out of the box with the chafa backend, but of course it doesn't on wayland (hangs on xwininfo, as noted in one of the bugs above). But chafa doesn't output pixels, so it doesn't really need the pixel size — `stty size` should be sufficient, right?

**Comment by mattdm** [comment]
Reviewers and enthusiasts seem to really like neofetch for their screenshots.

So, I'd like for it to display the Fedora logo nicely. We're particularly interested because we're just about to launch a refresh of the logo, and we've identified neofetch as somewhere where we'd like this to work nicely. I'd _really_ like this to work out of the box with the chafa backend, but of course it doesn't on wayland (hangs on xwininfo, as noted in one of the bugs above). But chafa doesn't output pixels, so it doesn't really need the pixel size — `stty size` should be sufficient, right?

**Comment by fl0gic** [comment]
Was having some issues on iTerm2, disabling `Show inline images at retina resolution` and `Disable potentially insecure escape sequences` in advanced preferences did the trick. Note that `Disable potentially insecure escape sequences` should be set to 'no', enabling the escape sequences.

**Comment by arcticlimer** [comment]
Trying to run neofetch from tmux using kitty terminal, it hangs at `Checking for graphics (10.0s max. wait)` for some seconds and then just prints the text without any image. And if I run it from outside a tmux session, it just works.

**Comment by DanielEliasib** [comment]
Just to add here, I'm having the same problems using the windows terminal with WSL 2 and with chafa backend, as it has been stated the problem is because neofetch can't get the terminal size. The only information I can add is that it works if I have gimp open, and completely hangs if I have nautilus open. 

Some logs, maybe they are useful for something.

[neofetchlog-gimp.log](https://github.com/dylanaraps/neofetch/files/6835708/neofetchlog-gimp.log)
[neofetchlog-naut.log](https://github.com/dylanaraps/neofetch/files/6835709/neofetchlog-naut.log)
[neofetchlog-solo.log](https://github.com/dylanaraps/neofetch/files/6835710/neofetchlog-solo.log)

**Comment by SNvMK** [comment]
Hm, not working in konsole/yakuake, tried pixterm, w3m and catimg. pixterm and catimg are displaying images (not in noefetch), dont know how to do so in w3m :(. But in neofetch, with --w3m/--catimg/--pixterm <img path> it is always shows ascii art. Imagemagick installed btw

**Comment by real-99** [comment]
> Sorry if this has been answered already, but what exactly is the deal with st and refusing to display w3m or sixel images outright with the alpha patch also present? Is it just due to transparency not being explicitly supported on either one?
> 
> Allegedly a few people can also get it to work in spite of the alpha patch being present, but I am yet to figure out how this could be accomplished.
> 
> EDIT: For the time being, ueberzug seems like the best solution without having to worry about disabling alpha on st.

I am not sure at 100%, but I think it's because st render is double-buffered, and how sixel/w3m draws images on a terminal is by drawing on the current term buffer

**Comment by clohr-vc** [comment]
Not working on `kitty 0.23.1` either. All dependencies installed, using the `icat` plugin directly works flawlessly with all image types. In `neofetch`, it just blinks for a second, then disappears.

**Comment by ghost** [comment]
> Not working on `kitty 0.23.1` either. All dependencies installed, using the `icat` plugin directly works flawlessly with all image types. In `neofetch`, it just blinks for a second, then disappears.

`neofetch --kitty` I think
