### ISSUE TITLE
Display AppImage files in "Packages"

### ISSUE THREAD

**Issue by UriHerrera** [dylanaraps/neofetch#1403]
## Description

Neofetch displays the packages installed in a given operating system. It shows the package manager, e.g., `dpkg.` Neofetch also displays the number of Snap and Flatpak packages, but it doesn't display any AppImages.

Neofetch can look for AppImage files in the folders `/Applications` or `/bin` for system-wide programs or `~/Applications` or `~/.local/bin` for user-specific programs.

#### Neofetch version
6.1.0

## Screenshot
![Nitrux_NX-1219814247087079426-20200121_204914-img1](https://user-images.githubusercontent.com/3053525/73792167-603d7500-4769-11ea-8af2-f4d371cba44e.jpg)

## Config file

https://gist.github.com/UriHerrera/a9a5fa59401b964cee0566ca45761b64

## Verbose log

https://gist.github.com/UriHerrera/2a1e19764d53ed71f84c20b2e73942ac

**Comment by dylanaraps** [comment]
Added support for `~/.local/bin` as it is the only location upstream recommends(?). The other directories you have mentioned don't seem to be standard across distributions(?).

Also, regardless, full support for listing appimages is difficult as they can be installed and run from anywhere. In reality, a better place to look would probably be the Downloads folder :-)

**Comment by chewblacka** [comment]
In case anyone is reading this wondering why it doesn't pick up their AppImages in `~/.local/bin` you need to have `appimaged ` installed on your system. Also currently only files ending in `.appimage` (case sensitive) are picked up by neofetch. I've submitted a pull request to correct this so that any variation of `.[Aa]pp[Ii]mage` is picked up:

https://github.com/dylanaraps/neofetch/pull/2006
