### ISSUE TITLE
Request: Specifying the number of cores and threads in the CPU row

### ISSUE THREAD

**Issue by VVakko** [dylanaraps/neofetch#1416]
I would like to suggest specifying the number of cores and threads in the CPU row by replacing (8) with (4C8T).
CPU: Intel i7-8559U (8) @ 2.70GHz
CPU: Intel i7-8559U (4C8T) @ 2.70GHz

**Comment by dylanaraps** [comment]
This is already possible through your neofetch config file with some shell code. Neofetch already supports logical OR physical cores for each OS and I'd rather not complicate the code further.

Thanks for opening this issue.

**Comment by clenchedteeth** [comment]
> This is already possible through your neofetch config file with some shell code. 

@dylanaraps could you elaborate on this please?

I made a small modification for a "both" option for my system and I really don't see how it is making the code overly complicated (I would happily make a PR including the other places):
```
            # Get CPU cores.
            case $cpu_cores in
                "logical" | "on") cores="$(grep -c "^processor" "$cpu_file")" ;;
                "physical") cores="$(awk '/^core id/&&!a[$0]++{++i} END {print i}' "$cpu_file")" ;;
                "both")
                    cores_logical="$(grep -c "^processor" "$cpu_file")"
                    cores_physical="$(awk '/^core id/&&!a[$0]++{++i} END {print i}' "$cpu_file")"
                    cores=${cores_physical}/${cores_logical}
                    ;;
            esac
```

I would find this very useful since I can never remember whether "4" refers to threads or cores.
