### ISSUE TITLE
Raspbery Pi 4. CPU temperature does not work.

### ISSUE THREAD

**Issue by 4k3or3et** [dylanaraps/neofetch#1463]
HI all

i would like to report a bug where on RPi4, CPU temperature is not showing up. You can easily check temp by command

`vcgencmd measure_temp | awk -F '=' '{print $2}'`

Any chance to implement that in future version?

**Comment by dylanaraps** [comment]
Send the full output of the `vcgencmd measure_temp` command.

**Comment by Rai** [comment]
on my RPi4, `vcgencmd measure_temp` output is:

`pi@raspberrypi:~ $ vcgencmd measure_temp
temp=43.0'C`

**Comment by TheThunderGuyS** [comment]
This also occurs on my Raspberry Pi 2. Right now I have added a custom field with `prin "CPU Temperature" "$(($(cat /sys/class/thermal/thermal_zone0/temp)/1000))°C"` in order to get the temperature (`cat /sys/class/thermal/thermal_zone0/temp` returns an integer containing temperature in celcius with a precision of 3 decimal places, which I then divide by 1000).

**Comment by notDavid** [comment]
My Raspberry Pi 3 Model B does not show the temperature either. In config.conf i've set `cpu_temp="C"` and in neofetch i see this output:  `CPU Temp: C`

Terminal:
```
$ vcgencmd measure_temp
temp=47.8'C
```

**Comment by SimonGr3dal** [comment]
I looked into this and found a solution.
I'm running Arch Linux Arm so this might be different on Raspberry Pi OS, but I'm pretty sure it applies.

Neofetch uses the following script to find the temperature on most systems.

``` sh
for temp_dir in /sys/class/hwmon/*; do
    [[ "$(< "${temp_dir}/name")" =~(coretemp|fam15h_power|k10temp) ]] && {
        temp_dirs=("$temp_dir"/temp*_input)
        temp_dir=${temp_dirs[0]}
        break
    }
done
```

Neofetch looks for directories in `/sys/class/hwmon/`
For each directory it will look for a `sys/class/hwmon/*/name` file, this name file must contain a certain string.
If the name file contains the correct string it will use the first available `/sys/class/hwmon/*/temp*_input` file

On my raspberry pi the temperature is in `/sys/class/hwmon/hwmon0/temp0_input`
So why doesn't it work in Neofetch?

Because the `/sys/class/hwmon/hwmon0/name` file contains "cpu_thermal" and not any of the "(coretemp|fam15h_power|k10temp)" in the above script

The solution is to add "cpu_thermal" to the regex so the bit of script becomes.

``` sh
for temp_dir in /sys/class/hwmon/*; do
    [[ "$(< "${temp_dir}/name")" =~(cpu_thermal|coretemp|fam15h_power|k10temp) ]] && {
        temp_dirs=("$temp_dir"/temp*_input)
        temp_dir=${temp_dirs[0]}
        break
    }
done
```

You can find your Neofetch script with `which neofetch` and just edit it with a text editor.

**Comment by ransur0t** [comment]
Thanks @simongredal !  After the edit to the temp_dir regex and toggling cpu_temp="C" in .config/neofetch/config.conf, temp is displayed!
