### ISSUE TITLE
Add Ubuntu Cinnamon logo

### ISSUE THREAD

**Issue by philipzae** [dylanaraps/neofetch#1506]
Please add the ascii of the logo for Ubuntu Cinnamon Remix.

**Comment by ItzSwirlz** [comment]
The ASCII Gen I used: https://www.ascii-art-generator.org/ Took out:


MMMMMMMMWNX0OxddoollllooddxO0XNWMMMMMMMM
MMMMMWNKOxdoolllllllllllllloodxOKNWMMMMM
MMMWN0kdolllllllllllllllloodxdoodk0NWMMM
MMWKkoolllllllllooooooooox0XXkolllokKWMM
MN0dollllllllooxkOOOOOOOkkO00xollllod0NM
N0dlllllllodxxxOOOkkkkO00K0OxollllllldON
0dollllllox0KkdooolllllooxOKKkdllllllod0
xollllllokKKkollloodddolllox0KOollllllox
oolodxkxx0KkollloxOKKOddxxdox00xollllloo
llox0XXOkKKxolodOKXKOkOKNNKkdxkdolllllll
olodxOOxxKKkookKXKOOOKNWMMWNXK0xollllllo
dolllooooOKKO0XX0O0XWWMMMMMMWN0dolllllod
kollllllodOXNX0OOXWMMMMMMMMWN0dollllllok
KkollllllloxkkkKNMMMMMMMMWNKkdollllllokK
WKkollllllllooxOKXXXXXXK0OOOOxolllllokKW
MWXOdollllllllloooddddoodkKXXkolllodOXWM
MMWNKxoollllllllllllllllooxkOxoloox0NWMM
MMMMWNKkdollllllllllllllllllooodkKNWMMMM
MMMMMMWWX0Oxdoooolllllloooodxk0XWWMMMMMM
MMMMMMMMMWNXKOxdoolllloodxO0XWMMMMMMMMMM

But SVG's wouldnt work and thanks to GitHub format this bad-but it is annoying due to the corners which are transparent are covered with M's and it's hard to find the difference between them.

**Comment by ItzSwirlz** [comment]
Just take this image and ASCII it

https://ubuntucinnamon.org/wp-content/uploads/2020/04/logo-e1586265765207.png

**Comment by ItzSwirlz** [comment]
Closed in commit https://github.com/dylanaraps/neofetch/commit/3c63ac1d4a69cb032f112a1586907138e69475ce

**Comment by ItzSwirlz** [comment]
Actually lubuntu and ubuntu-mate have the same issues... I'll open a bug report for it.

**Comment by ItzSwirlz** [comment]
Further discussion regarding above should happen at #1509 . Close bug report.
