### ISSUE TITLE
Neofetch reports resolution of VR headset instead of monitor

### ISSUE THREAD

**Issue by dllu** [dylanaraps/neofetch#1639]
## Description

Neofetch shows the resolution of my Valve Index instead of my monitor. Screenfetch correctly reports resolution of monitor. On Arch Linux right now.

It seems neofetch simply goes through `/sys/class/drm/*/modes` and returns the first one. But it should return the largest one instead. I suspect this may affect multiple monitors with different resolutions but I don't have monitors of different resolutions to experiment with. That should be an easy fix.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version

7.1.0

## Screenshot

![pic](https://s.dllu.net/N7pAIVHikf0MDrHf.png)

## Config file

Not relevant

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/5742561/neofetchlog.txt)

**Comment by dylanaraps** [comment]
> It seems neofetch simply goes through /sys/class/drm/*/modes

Neofetch only goes through drm modes if xrandr, xwininfo or xdpyinfo are unavailable. This is X11 specific so the DRM codepath *is* executed in Wayland and the tty. Wayland support is tricky since every compositor does its own thing (dbus for gnome(?)/kde(?) (different apis?), swaymsg for sway(?)(other wlroots compositors(?), etc).

> and returns the first one.

It appends all entries to a list. I ~~may~~ have spotted a bug where this list is being truncated
to a single entry however (so this is a bug).

**Comment by dllu** [comment]
good catch! thanks for the fix
