### ISSUE TITLE
Bedrock Linux neofetch bug (on gentoo)

### ISSUE THREAD

**Issue by MuhammedTaha02** [dylanaraps/neofetch#1671]
## Description
Although the package number is 997, it appears as 3988 in neofetch.

## Neofetch version
Neofetch version: 7.1.0

## Screenshot
![image](https://user-images.githubusercontent.com/62564400/106178050-f603b880-61a1-11eb-961f-b45c7f447408.png)

## Config file
Default

## Verbose log
https://paste.centos.org/view/8f867f0c
Alternative:
https://pastebin.pl/view/1f833fd5

**Comment by MuhammedTaha02** [comment]
drwxr-xr-x 23 root root 4096 Jan 28 19:06 gentoo/
lrwxrwxrwx  1 root root    6 Jan 28 19:05 hijacked -> gentoo/
lrwxrwxrwx  1 root root   23 Nov 10 14:48 init -> /bedrock/run/init-alias/
lrwxrwxrwx  1 root root   21 Nov 10 14:48 local -> ../cross/.local-alias/

Neofetch counts the packages in these 4 folders repeatedly and the value appears to be 4 times

**Comment by paradigm** [comment]
The proper fix here might be to filter out symlinks from that bit of code.  That will add a lot of code/complexity compared to the current one-liners in there.  I'd have to play with it for a bit to find a clean enough solution for Dylan's tastes.

Your proposed PR is not a good general fix, as:

- That explicitly breaks counting for other strata.
- The `hijacked` alias is a default, but not actually required.  You can `brl remove` it.  The Bedrock system I'm using to type this message doesn't have a `hijacked` alias.

If your goal is _only_ to get the hijacked stratum's package count, you can use `strat -r hijacked neofetch`.

**Comment by MuhammedTaha02** [comment]
> The proper fix here might be to filter out symlinks from that bit of code. That will add a lot of code/complexity compared to the current one-liners in there. I'd have to play with it for a bit to find a clean enough solution for Dylan's tastes.
> 
> Your proposed PR is not a good general fix, as:
> 
> * That explicitly breaks counting for other strata.
> * The `hijacked` alias is a default, but not actually required.  You can `brl remove` it.  The Bedrock system I'm using to type this message doesn't have a `hijacked` alias.
> 
> If your goal is _only_ to get the hijacked stratum's package count, you can use `strat -r hijacked neofetch`.

The method I mentioned does not break any order. For other package managers, I can get the package count without any problem. But since I use gentoo and there are 3 symlinks + 1 default directors on gentoo, the package count seems 4 times higher. If I switched to fedora this time it would look 4 times as much

Look at!
![image](https://user-images.githubusercontent.com/62564400/106352650-eb5a3800-62f5-11eb-81ea-38944c0d6ab4.png)

**Comment by paradigm** [comment]
> The method I mentioned does not break any order.

I'm not exactly sure what you mean by "order," but https://github.com/dylanaraps/neofetch/pull/1672 most definitely breaks counting any of the `${br_prefix}` package managers for strata named/aliased anything other than "hijacked."  Have you actually tried your PR out to see how it acts?  Try:

1. `brl fetch gentoo -n test-gentoo` then see if `neofetch` with your changes includes `test-gentoo`'s packages.  If you want to, you can `brl disable test-gentoo && brl remove test-gentoo` to remove the test stratum afterwards.
2. `brl remove hijacked` then see if `neofetch` with your changes counts packages correctly.  If you want to, you can `brl alias <hijacked-stratum> hijacked` to recreate the alias afterwards, replacing `<hijacked-stratum>` as appropriate.  I'm guessing it should be "gentoo" for you.

> For other package managers, I can get the package count without any problem

The problem I'm raising with your PR isn't for other _package managers_ but for other _strata_.

> But since I use gentoo and there are 3 symlinks + 1 default directors on gentoo, the package count seems 4 times higher.

I agree `neofetch`'s current strategy for `${br_prefix}` packages miscounts as a result of the symlinks Bedrock uses for aliases.  I'm not saying `neofetch` is counting packages on Bedrock correctly.  I'm saying your PR breaks `neofetch`'s ability to count packages on Bedrock in a different way.

> If I switched to fedora this time it would look 4 times as much

If you mean hijack a Fedora system so that Bedrock creates three aliases for "fedora" by default, then no, that's not the case.  The bug here is specific to the combination of Bedrock aliases _and_ package managers for which `neofetch` uses `${br_prefix}`.  Again, have you actually tried your hypothetical here?  Try:

- `brl fetch fedora -n test-fedora`
- `strat test-fedora dnf install neofetch`
- Reboot and select neofetch's init (to direct the `init` alias to `fedora`)
- `strat test-fedora neofetch` (to direct the `local` alias to `fedora`)

and see if the you actually get three times the expected `rpm` package count.

-----

I put up my own proposed fix at https://github.com/dylanaraps/neofetch/pull/1675

I wouldn't be surprised if Dylan shoots it down over style choices or some edge case I failed to consider, but it does properly handle the issues I've raised with your PR.
