### ISSUE TITLE
neofetch does not relinquish console

### ISSUE THREAD

**Issue by bitshiftnetau** [dylanaraps/neofetch#1942]
## Description

If you're suggesting a new feature then just a description will suffice.

- [ X ] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
most recent on Arch Linux

## Screenshot
unattainable

## Config file
unattainable

## Verbose log
unattainable

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

The issue is with neofetch not relinquishing the console on Arch Linux, startx, with i3 launcher.

**Comment by yuri-norwood** [comment]
By "not relinquishing" do you mean that the shell prompt never appears? i.e. NF hangs and doesn't exit?

**Comment by dylanaraps** [comment]
Open a new issue following the template.

**Comment by bitshiftnetau** [comment]
@yuri-norwood yes that is correct. 

It appears to be something wrong in the config. 

@dylanaraps sure bud, I'll do that when I get access to the system that I'm locked out of due to neofetch.

**Comment by yuri-norwood** [comment]
@bitshiftnetau, sounds like you may have a faulty `.xinitrc` file if the hang is happening at startx, this *might* be due to neofetch, but it also *might* be due to your i3 setup, or anything else in the `.xinitrc`. It's not clear the neofetch is at fault here, from your description it looks like you execute neofetch from your `.xinitrc`, which successfully runs, and something that happens *after* NF exits is causing the hang. [There are many possible causes](https://duckduckgo.com/?q=arch+linux+startx+hangs).

If this is a fresh install of arch you may have missed a step during installation, if you still have your boot USB handy, I'd recommend chrooting into your system to do some [troubleshooting](https://wiki.archlinux.org/title/General_troubleshooting#Boot_problems).

I'd suggest chrooting in anyways to get at the neofetch config, as without that there isn't much that can be done really. 😉
