### ISSUE TITLE
Temporarily disable neofetch

### ISSUE THREAD

**Issue by loewal** [dylanaraps/neofetch#1984]
## Description

I would like to temporarily disable neofetch.
I can't find an entry in bashrc nor zshrc...where is it called?

**Comment by Abhishek12345679** [comment]
what do you mean by "disable"

**Comment by loewal** [comment]
Prevent it from starting automatically.
I could not find any entry where it is started.
Neither any service. Strange! In macOs I had to place the command in .zshrc.
On my Raspberry Pi’s Neofetch is started automatically. Sometimes I want to prevent that.

Thnx!

**Comment by WSLUser** [comment]
It's compiled in with the distro. You'd need to look up your distro's documentation on stopped automatic startup services (not specific to neofetch).

**Comment by loewal** [comment]
I listed running services with:

systemctl --type=service

Nothing with neofetch.

Helas….

**Comment by WSLUser** [comment]
Then it shouldn't be running. I'd look into what neofetch needs to run before it can be executed. As far as I'm aware that's bash and ncurses. I don't think you'd want to stop bash from running automatically unless you're using another shell by default like zsh or fish.

**Comment by yuri-norwood** [comment]
@loewal Are you running vanilla raspian, or do you have a different OS installed in your raspberrypi?

**Comment by loewal** [comment]
Debian Buster, Raspbian, Odroid etc. All installed via apt.

Why all those questions?
 Please: how to prevent from automatically launching Neofetch.
Never ever got this question?
I ask this because loginprocedure can be slow with older raspberries.

**Comment by yuri-norwood** [comment]
> Why all those questions?

@loewal because neofetch is just a script, it doesn't install itself into your system auto start services (unless you or the distro maintainers put it there), nf simply runs when it is called.

Normally nf is called in a shell start up file, such as `~/.profile` (or in the case of your Mac, `~/.zshrc`). We're basically asking which start up files you have, if any of them have nf in them, and whether they were packaged as part of the OS distribution.

I'd recommend looking through the home directory for any dotfiles that may be called during startup, and reading their code for what they are doing that might be slowing down your start up times.
