### ISSUE TITLE
Add support for Peropesis Linux

### ISSUE THREAD

**Issue by syswraith** [dylanaraps/neofetch#2414]
# [Peropesis Linux](https://peropesis.org/)
> Peropesis is a small-scale, minimalist, command-line-based Linux operating system. It's an incomplete system, but it's constantly being improved. Also, it is a free operating system created from a free software. The Peropesis project includes the operating system itself and this website, that contains all the necessary information about this operating system.

## ASCII art (copy pasted from the logo) on the main page
```
####  #### ####   ###   ####  ####  #### #  ####
#   # #    #   # #   #  #   # #     #    #  #
####  ###  #### #     # ####  ###     #  #    #
#     #    #  #  #   #  #     #        # #     #
#     #### #   #  ###   #     #### ####  # ####
```

**Comment by FabioLolix** [comment]
Peropesis is proprietary OS created from FOSS programs, nothing is public relative to the OS development and creation

**Comment by hykilpikonna** [comment]
I'm looking at adding support to it.

First thing I've noticed: it doesn't support UEFI?

Then, there are no *release files (e.g. /etc/os-release) identifying this distro:

<img width="1392" alt="image" src="https://github.com/dylanaraps/neofetch/assets/22280294/37d2c292-5cae-4931-bbc1-994914e3cc1c">

**Comment by hykilpikonna** [comment]
Ok, I added support by checking if any file in `/usr/bin` includes "peropesis". (since there is a file `/usr/bin/x86_64-peropesis-linux-gnu-c++` that can identify peropesis)

<img width="462" alt="image" src="https://github.com/dylanaraps/neofetch/assets/22280294/2b811882-5711-4f2d-b085-f09690cff023">

<img width="1392" alt="image" src="https://github.com/dylanaraps/neofetch/assets/22280294/4dafd73f-edf7-42c8-b67a-2ce285f4dbfd">

If you know a better way please let me know.

**Comment by syswraith** [comment]
This is perfect. Thank you.
