### ISSUE TITLE
Images not showing on debian testing

### ISSUE THREAD

**Issue by BatyaMedic** [dylanaraps/neofetch#332]
## Description
w3m-img version
Version: 0.5.3-29
Imagemagick version
Version: 8:6.8.9.9-7.2

## System Information
OS: Debian GNU/Linux testing (stretch) x86_64
Kernel: 4.6.0-1-amd64
CPU: AMD FX-4350 (4) @ 4.2GHz
GPU: NVIDIA GeForce GTX 660
#### Neofetch version
1.7-1
#### Operating system
OS: Debian GNU/Linux testing (stretch) x86_64

## Verbose log
http://pastebin.com/3U5pVUxD

**Comment by konimex** [comment]
Screenshots, please?

**Comment by BatyaMedic** [comment]
![2016-09-14 21-53-27](https://cloud.githubusercontent.com/assets/9035722/18525578/1fc417c4-7ace-11e6-9783-852e95d39a39.png)

**Comment by BatyaMedic** [comment]
git version are showing image in terminator,but if a choose another window image dissapear

**Comment by dylanaraps** [comment]
The image disappearing on focus change is a quirk of w3m-img and terminator and it's nothing I can fix. I recommend using another terminal emulator if you'd like to use image mode. See this wiki page for getting images in the terminal to work properly. 

https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal 

I'm not going to provide support for anything that's already fixed in master. I'll release a new version of neofetch in October, we're well overdue at this point. I'd release it earlier but I'll be away from home for the remainder of this month.

Closing this as it's not our bug.
