### ISSUE TITLE
emotion-generic

### ISSUE THREAD

**Issue by JosefStylin** [dylanaraps/neofetch#448]
## Description

'neofetch' doesn't bring back any image

## System Information

refer to screenshot

#### Neofetch version

8d98c4f

#### Operating system

Ubuntu 16.04.1 LTS x86_64

## Screenshot

https://i.imgur.com/9Qipkgq.png

## Verbose log

Not sure if this is what you were looking for: https://gist.github.com/JosefStylin/72353c12b3607e3abdc1b3c5ce5b9d3a

**Comment by dylanaraps** [comment]
The log file tells me that neofetch is working correctly and the error message is coming from `tycat`. I googled the error message and came across these links: 

- http://stackoverflow.com/questions/35686338/terminology-emotion-generic-error-when-viewing-images
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773057
- http://forums.bodhilinux.com/index.php?/topic/9730-terminology-generic-player/
- https://sourceforge.net/p/enlightenment/mailman/enlightenment-users/thread/20130531095412.14399d897acbc42a53a08dc2@rasterman.com/

It looks like you're missing a dependency of `terminology` which is required for images to work. It's called `emotion_generic_players`. Installing the program below should solve the issue.

https://git.enlightenment.org/core/emotion_generic_players.git/

If the issue still isn't solved then I'm going to close this since it isn't related to neofetch. You should open a bug report on Ubuntu's tracker or Terminology's tracker.

**Comment by JosefStylin** [comment]
Once I've installed VLC the gnome-terminal started working with neofetch. terminology still gives the same error. I'll try to pursue this on the terminal side.
