### ISSUE TITLE
Identify the package manager

### ISSUE THREAD

**Issue by picsi** [dylanaraps/neofetch#483]
It would be useful to have the package manager identified. Many users take pride in their choice for pkg mgmt :)

Related: https://github.com/KittyKatt/screenFetch/issues/346

**Comment by konimex** [comment]
Is it *really* necessary?

Most distros have just 1 *obvious* package manager (like `dpkg/apt`, `rpm`, `pacman`) or whatever. And some systems may have two package managers (for instance, my system has `emerge` and `rpm` installed).

I think this will be unnecessary, since if we detect distro anyway, people will know what *default* package manager the users use.

**Comment by picsi** [comment]
It'd be more useful to output if the user has another package manager other than the default, no?

**Comment by dylanaraps** [comment]
This shouldn't be too hard to implement assuming I don't run into any surprises. If I manage to get it working it **will** be optional and probably off by default. 

Here are a few ideas for the output:

```sh
Packages: 100 (pacman)
Packages: 650 (apt)
Packages: 800 (pacman, apt)
```

**Comment by dylanaraps** [comment]
I'm struggling to find a simple way to implement this, every approach I've tried so far has added far too much complexity to the package function.

**Comment by dylanaraps** [comment]
I can't find a simple way to implement this and like @konimex, I don't think it's really necessary.

Thanks for opening this issue!
