### ISSUE TITLE
Not detecting MATE on Arch

### ISSUE THREAD

**Issue by edgard** [dylanaraps/neofetch#582]
## Description

Using MATE 1.16.1 (GTK2, the default install) from Arch. It's not detecting the DE, therefore, not detecting themes, icons, etc.

#### Neofetch version

2.0.2

## Screenshot

Neofetch: https://u.teknik.io/frZB7.png
Mate appearance settings: https://u.teknik.io/e27kH.png

## Verbose log

https://p.teknik.io/4DC91

**Comment by konimex** [comment]
I'm assuming the output of `echo $XDG_CURRENT_DESKTOP` is empty?

What's the output of `xprop -root`?

**Comment by dylanaraps** [comment]
Also, how are you starting MATE?

**Comment by edgard** [comment]
@konimex yeah, XDG_CURRENT_DESKTOP is empty.

output of xprop -root: https://p.teknik.io/i1kB3

@dylanaraps starting from lightdm. are you using mate or mate-gtk3? I think on gtk3 it works properly.

**Comment by edgard** [comment]
screenfetch is detecting correctly, so the information is out there somehow :D

https://u.teknik.io/IEqBm.png

**Comment by dylanaraps** [comment]
I'll install lightdm and see if I can reproduce this. :)

**Comment by mstraube** [comment]
On my Arch system MATE detection (and also KDE) doesn't work, too. 

$XDG_CURRENT_DESKTOP is not empty, 

but it turned out that in line [539](https://github.com/dylanaraps/neofetch/blob/ee72084a9ae6361fca0837ecbfc187894f6ecde9/neofetch#L539) `get_wm` is not executed. I have to change it to either 

`[[ "$wm_run" -ne 1 ]] && get_wm` 
or 
`((wm_run != 1)) && get_wm`

Then the second problem is line [542](https://github.com/dylanaraps/neofetch/blob/ee72084a9ae6361fca0837ecbfc187894f6ecde9/neofetch#L542). I think it should be `de="${XDG_CURRENT_DESKTOP/'X-'}"`

Without these two changes `$de` and `$wm` are both empty and the function is left in line [559](https://github.com/dylanaraps/neofetch/blob/ee72084a9ae6361fca0837ecbfc187894f6ecde9/neofetch#L559)

**Comment by dylanaraps** [comment]
Thanks @mstraube!

Can you test out #575 and let me know if it fixes the issues?

**Comment by edgard** [comment]
#583 fix for me! awesome, thanks guys!!

**Comment by dylanaraps** [comment]
Thanks for testing it. :)

**Comment by mstraube** [comment]
Works for me too.
Sorry for the delay, it was too late yesterday ;)
