### ISSUE TITLE
ArchBox detected as Arch

### ISSUE THREAD

**Issue by mstraube** [dylanaraps/neofetch#634]
## Description
I tried to add support for [ArchBox Linux](https://archbox-linux.github.io/)

It's detected as Arch Linux by `lsb_release`, but has ArchBox Linux in `/etc/os-release`.
```
archbox@archbox ~/neofetch (git)-[master] % lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

archbox@archbox ~/neofetch (git)-[master] % cat /etc/os-release 
NAME="ArchBox Linux"
ID=arch
PRETTY_NAME="ArchBox Linux"
ANSI_COLOR="0;32"
HOME_URL="http://archbox-linux.github.io/"
SUPPORT_URL=""
```
I'm not sure how to fix this without breaking anything.

I also made two versions for an [ascii logo](https://gist.github.com/mstraube/f2bafc875ffb857b4237fd9b0dd0f815), probably improvable.  ;)

Edit:
On second thought, maybe ArchBox is so small and unknown that it's not worth adding..

**Comment by konimex** [comment]
This is the same case as Antergos as they don't even bother to supply their own lsb_release file/package. We had deleted support for lsb_release and it proved to be useful in detecting distros (as distros filled them in properly). I don't think we should add any exception case/if when an upstream distro (i.e. Arch for Antergos) is detected.

**Comment by dylanaraps** [comment]
I doubt they'll fix `lsb_release` since ArchBox is just an installer for vanilla Arch Linux that installs Openbox, Tint2 and a some other packages. What you're left with after installing is a vanilla Arch system running some extra packages.

For ArchBox to fix `lsb_release` they are going to have to repackage `lsb_release` with the same modifications they made to `/etc/os-release`. This will never happen since Archbox are only using vanilla Arch packages (Not repackaging anything) and the GitHub repo hasn't been updated in 7 months.

Source: https://archbox-linux.github.io/about/

We can still add support for ArchBox and detection will work as long as the user doesn't have `lsb_release` installed. Arch Linux doesn't install it by default and most people won't have an incentive to install it. This is how detection for Antergos works currently.

This is the best solution to a non-issue in my opinion.

**Comment by dylanaraps** [comment]
Done.

Great job on the logo. :)

**Comment by mstraube** [comment]
Thanks.

Now I understand the `lsb_release` thing. Unfortunately the lsb-release package is installed by default in ArchBox.

**Comment by dylanaraps** [comment]
It's not listed on the website for ArchBox. ><

I'll try and come up with another solution.
