### ISSUE TITLE
iTerm2: Images not working inside tmux

### ISSUE THREAD

**Issue by mike3run** [dylanaraps/neofetch#678]
## Description

Hey there I'm having problems displaying an image inside tmux with iterm2. Im on a Mac machine.
When outside tmux it displays the image just fine but in tmux i just get a blank space.
It's probably a silly fix but I haven't been able to detect how to do it properly.

Thanks!

## Screenshot
First is outside tmux:
![screen shot 2017-03-22 at 13 47 46](https://cloud.githubusercontent.com/assets/7088511/24217659/34d190c0-0f06-11e7-9f48-98847e41c34e.png)

Now inside 😢 
![screen shot 2017-03-22 at 13 47 32](https://cloud.githubusercontent.com/assets/7088511/24217667/3d145236-0f06-11e7-813b-16817bde223a.png)

## Config file
http://pastebin.com/M6PERYgz

## Verbose log
http://pastebin.com/d01Ccq0r

**Comment by dylanaraps** [comment]
Fixed.

Please let me know if the issue still occurs.

**Comment by mike3run** [comment]
I think homebrew still hasn't updated it shows like i still have the most recent build...

I'll wait a bit longer and retry.

Or maybe you should bump the version number?

**Comment by mike3run** [comment]
Also thanks a lot for the speedy response i appreciate that a lot 💁

**Comment by dylanaraps** [comment]
Homebrew doesn't update till I push a new release. 

I think there's a way to grab the latest git version though.

Try:

- `brew upgrade --build-from-source neofetch`
- `brew install --devel neofetch`

**Comment by mike3run** [comment]
That's not working though 😞 

![screen shot 2017-03-22 at 15 51 32](https://cloud.githubusercontent.com/assets/7088511/24222368/7069c8a8-0f17-11e7-8a7f-95ab37cbe328.png)

**Comment by mike3run** [comment]
why not release that minor fix as 3.0.2 ?

**Comment by iandrewt** [comment]
Try `brew install neofetch --HEAD`

**Comment by dylanaraps** [comment]
I'll release a new version soon, I just don't have the time right now. There's a lot of prep I need to do before I can release an update, see the checklist here:

https://github.com/dylanaraps/neofetch/issues/613#issuecomment-276009486

**Comment by mike3run** [comment]
Thanks @iandrewt that did the trick

**Comment by mike3run** [comment]
@dylanaraps that fix didnt' work still although now my terminal beeps and shows something instead of the image in tmux:

![screen shot 2017-03-22 at 15 57 51](https://cloud.githubusercontent.com/assets/7088511/24222679/7a6343ec-0f18-11e7-80ea-78371b08c825.png)

Config file: http://pastebin.com/M6PERYgz
Log: http://pastebin.com/tj11WUFx

**Comment by iandrewt** [comment]
Also note that when using `--HEAD` with Homebrew, it doesn't check for updates for that package when using it. If you want to get back to the release version, you'll need to uninstall it (`brew uninstall neofetch`) and reinstall it (`brew install neofetch`). I'd advise you don't do that until 3.0.2 is released though.

**Comment by dylanaraps** [comment]
Weird.

Does this script work? (This is from iTerm2's repo)

https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/imgcat

Usage is `./imgcat /path/to/img`.

**Comment by konimex** [comment]
To be fair, I think it would be better to release it as 3.1 instead of another minor bugfix version because neofetch has addef new features *and* still have some milestones to do (from the TODO).

On 23 March 2017 4:52:20 AM GMT+07:00, Miguel Palau <notifications@github.com> wrote:
>why not release that minor fix as 3.0.2 ?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanaraps/neofetch/issues/678#issuecomment-288551473

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by iandrewt** [comment]
I just tested `imgcat` in iTerm2 with tmux, doesn't work (oddly, given one of the main features of iTerm2 is tmux integration)

**Comment by mike3run** [comment]
I downloaded imgcat with curl then ran the command nothing happens

![screen shot 2017-03-22 at 16 05 16](https://cloud.githubusercontent.com/assets/7088511/24222891/5ef371d0-0f19-11e7-864a-32d92713062b.png)

**Comment by dylanaraps** [comment]
It might be worth opening an issue on iTerm2's bug tracker if the official script is broken too.

**Comment by jorgegonzalez** [comment]
https://gitlab.com/gnachman/iterm2/issues/3898

This seems to be a known problem with tmux. George Nachman (iTerm2's creator) said:

_"It's a limitation of tmux. The size of the image is determined by iTerm2, and that in turn determines where the cursor moves to after the image is displayed. tmux can't perform the calculation to determine image size because it's contingent on font size (if a single character is, say, 10x10, then a 50x50 image will be 5 chars wide by 5 tall). tmux has no notion of font size, so I don't know how it could properly support images. That's why it works in tmux integration mode but not in plain-old tmux."_

And just yesterday:

_"I'm afraid it'll be hard to make it work in tmux. iTerm2 is the only terminal that supports inline images, while tmux has much wider adoption, so they're unlikely to be interested in an iTerm2-only patch."_

**Comment by dylanaraps** [comment]
Closing this then, thanks for finding that. 👍

**Comment by mike3run** [comment]
Haha loved the label thanks for the heads up man!

**Comment by kamontat** [comment]
@mike3run What terminal theme that you use? so beautiful...

**Comment by mike3run** [comment]
@kamontat it's iterm with oceanic next color scheme my dotfiles are on my profile if you want to take a look

My shell is fish. But I have config files there for zsh

Thanks for liking it

**Comment by wernight** [comment]
Chrome secure shell also supports it (outside of Tmux), and it's getting more and more used as it's part of Chromebooks and Chrome.

See also https://chromium.googlesource.com/apps/libapps/+/master/hterm/etc/hterm-show-file.sh

**Comment by jsatk** [comment]
I ran into this issue. After hours of digging this is the first real thread with quality info. Sad the result is "can't work" but glad to have found the solution. Thanks @jorgegonzalez .

**Comment by typkrft** [comment]
> Try `brew install neofetch --HEAD`

This should be stickied or added to the wiki for macOS people having issues with images because `brew install neofetch` would not display images. Brew installed 6.1.0. It did not have the Catalina Code name like the HEAD does. 

`brew install neofetch --head` 

worked with a default config in iterm.

iTerm Build 3.3.6
macOS Catalina 10.15.1 (19B88)
