### ISSUE TITLE
iTerm2 image rendered with wrong size in split panel

### ISSUE THREAD

**Issue by bauen1** [dylanaraps/neofetch#686]
## Description

When running neofetch from a iTerm2 split panel, the image is drawn as if neofetch was running in a terminal window just for its own, the solution would be to find a replacement for \033[14t that returns the correct terminal size inside split panels

#### Neofetch version
3.0.1
## Screenshot
![bildschirmfoto 2017-03-31 um 22 25 19](https://cloud.githubusercontent.com/assets/16723362/24568152/1bd255ca-1661-11e7-92b6-86e8874aa924.png)

**Comment by dylanaraps** [comment]
The same issue occurs with `tmux` and `screen` in all other modes that require the terminal window size to function. Unless we can find a way to get the split size in pixels universally there's no way for me to fix this.

There's more to it than finding a replacement for `\033[14t`. If the escape sequence isn't supported by the terminal (Which isn't uncommon) we fall back to finding window size using X tools on all OS that use an X server. Any combination of the following tools is used based on what is available in `$PATH`: `xdotool`, `xwininfo`, `xprop`, `xdpyinfo`. 

I think it's going to be near impossible to get neofetch's image mode working correctly with splits. Other than iTerm2, `tmux` and `screen` there are a lot of other programs/terminals that provide splits and we would need to find a proper solution to support all of them.

Terminal window size is required for us to be able to size the image correctly. Some backends take pixels for sizing, others take columns/rows and iirc one of the backends takes a percentage value. We need the window size to be able to calculate pixels, columns/rows and percentages.

If there is another escape sequence that works like `\033[14t` then it would need to be implemented by whatever program/terminal is providing the splits. If the splits are being created by a terminal program such as `tmux` then the parent terminal emulator won't know the splits exist. 

I'll do some digging and see if I can find anything more but the most likely outcome for this issue is me closing it as a `wontfix`.

**Comment by dylanaraps** [comment]
Tmux:

- We can use a `tmux` command to print the sizes of all of the splits. We can then parse this to get the number of Rows and Columns big the split is.
    - `tmux list-panes -F "#{pane_width}x#{pane_height}x#{pane_active}"`
        - Format: `000x000x1`
        - Note: The last `x0` will be a `1/0` depending on whether or not it is the active split.

**Comment by gilgameshskytrooper** [comment]
I've tried messing around with a few things.
check out my progress here: [https://github.com/gilgameshskytrooper/neofetch](url)
Specifically, I commented some thoughts in tmuxintegrationscript

Now, I am able to get the "columns and rows" out of tmux via the tmux list-panes -F "#{pane_width}x#{pane_height}x#{pane_active}" command, but this is not very helpful by itself. 

`currentpaneid="$(expr "$(tmux display -pt "${TMUX_PANE:?}" '#{pane_index}')" + "1")"`
will get the id of the current active pane (which should be fine because if neofetch is executed as a shell init script, then that "pane" will be active.

Next, using, 
`dimentionsofthepane="$(tmux list-panes -F "#{pane_width}x#{pane_height}x#{pane_active}" | awk "NR==${currentpaneid}")"`
gets the dimentions of the current pane (by specifying NR by the index+1, we will get the index+1'th result. Which is what you want.

Next,
`dimentionsofthepan2=${dimentionsofthepane%x*}
pane_rows="${dimentionsofthepan2%x*}"
pane_columns="${dimentionsofthepan2#*x}"
`
gets the actual rows and columns out of that data structure and...
`window_rows="$(tmux display -p "#{window_height}")"
window_columns="$(tmux display -p "#{window_width}")"
`
gets the dimensions of the current windows height and width.

My progress is basically to be able to do pane_width/window_width to get a the actual  pane_height/window_height that pane occupies.

Now if we can somehow get the pixels as REAL PIXEL values, not columns and rows, then we can multiply the above ratios to get the correct size in pixels. (Or at least thats what I think neofetch needs for the image backends to work properly: if this is not the case, and you just need the ratio between the tmux pane and the rest of the tmux window, then hurrah, this should solve the issue).

Now I've tried using a few commands to get the screen resolution in pixels, but none of them really work. For example, 
`window_resolution_x=$(xdpyinfo | awk -F '[ x]+' '/dimensions:/{print $3}')
window_resolution_y=$(xdpyinfo | awk -F '[ x]+' '/dimensions:/{print $4}')
`
Gives me the max potential dimensions for my screen (which is not what I want, I need the actual size).

I've looked into way to get this directly out of tmux, but it doesn't seem they support this feature. Furthermore, neither ncurses, nor any other library tmux depends on can directly get you real pixel information about the session.

Hence, the below code is wrong, but just to show you what I meant to do, I will add it here anyways:
`term_height=$((window_resolution_y*pane_rows/window_rows))
term_width=$((window_resolution_x*pane_columns/window_columns))`

By multiplying the real dimensions by the pane dimentions, then dividing the window dimentions, theoretically it should give us a near perfect estimation of the actual dimensions of a Tmux pane. If neofetch is run at the start of the shell, then this should be accurate on a per pane basis every time neofetch is called. So no need to further specify rows/columns, or how they relate to the rest of the window, just need real pixels (I think, tell me if I'm wrong.

I will go ahead and put in a pull request from my fork, but I don't think it is usable yet so throw it in a dev branch or just take what you need and copy paste.

**Comment by gilgameshskytrooper** [comment]
Rereading what you said about tmux, I change my conclusion: tmux list-panes -F "#{pane_width}x#{pane_height}x#{pane_active}" will not give you what you need. By pane_width and height, I think it is returning returning columns and rows, not total pixels.

I could be wrong, and I am bad at bash.
