### ISSUE TITLE
Not using ubuntu-gnome ASCII art on ubuntu gnome 17.04

### ISSUE THREAD

**Issue by Swedneck** [dylanaraps/neofetch#839]
## Description
When running Neofetch without any arguments it displays the ubuntu logo art instead of the ubuntu-gnome art. Im running ubuntu gnome 17.04, freshly installed since yesterday.

#### Neofetch version
3.0.1
## Config file
unmodified

## Verbose log
https://pastebin.com/pHdHvF70

**Comment by dylanaraps** [comment]
This is working as intended. All Ubuntu flavours are all labelled as stock Ubuntu underneath. There's no way to distinguish the difference between Ubuntu-GNOME and Ubuntu with GNOME as its DE.

The flavour logos were added so that you can set them yourself (*It's better than nothing*).

Example:

```sh
neofetch --ascii_distro ubuntu-gnome
```

Note: You can also set this in your config file to make it persist.
