### ISSUE TITLE
Add current weather display

### ISSUE THREAD

**Issue by MarcNME** [dylanaraps/neofetch#862]
I think it would be a nice feature, when it could display the current weather for your location.
Please consider.

**Comment by TokyoChopSquad** [comment]
I think this could be done by calling in another program. Neo fetch allows you to trigger custom commands so I "Think" you could have what you want to be done in a roundabout way. I'll take a look to see if I can get that working.

**Comment by konimex** [comment]
I think this is way too out-of-scope for neofetch.

**Comment by TokyoChopSquad** [comment]
I think Konimex is correct on this. The thing to do would be to add a command to the bashrc / zshrc after neofetch. 

I did find a nice ascii text weather command but I've since then lost it. I'll look for it again.

**Comment by TokyoChopSquad** [comment]
Potentially this could work. 

curl wttr.in/your_location

**Comment by dylanaraps** [comment]
Here's a one-liner for your neofetch config that adds weather support:

```sh
prin "Weather" "$(curl wttr.in/?0?q?T | awk '/°(C|F)/ {printf $3 $4 " ("a")"} /,/ {a=$0}')"
```
It uses your current location, works with Celsius and Fahrenheit and looks like this:

![2017-12-14-141345_1659x1032_scrot](https://user-images.githubusercontent.com/6799467/33973653-2011692c-e0d8-11e7-878c-be33e0168bd7.png)

Note: This won't be added to Neofetch but will be added to a wiki page so that other users can add it to their configs.
