### ISSUE TITLE
Option to disable cropping

### ISSUE THREAD

**Issue by karasuma-chitose** [dylanaraps/neofetch#865]
It'd be nice if I could display a narrower image without it getting cropped to a square.
I tried making it into a transparent squared image that contains the original image on the left side with GIMP so it wouldn't get cropped and used --gap to move the text to the left over the transparent part, but that part of the text probably went under the transparent part probably and disappeared.

**Comment by konimex** [comment]
Doesn't `--crop_mode none` do this exact thing?

**Comment by dylanaraps** [comment]
That disables cropping but the image is still displayed as a square. I'll look into the code to see how easy it is to unrestrict the image shape.

**Comment by dylanaraps** [comment]
I've pushed a fix and you can now use `--size none` to display the image using the original aspect ratio. If the image fits inside the display area it won't be resized otherwise it'll be scaled down to fit the area.

I may make `--size none` the new default with an option to get the square mode using `--size square`. I haven't decided yet.

Examples (`neofetch --w3m /path/to/img.jpg --size none`):

![2017-12-13-103353_1602x1108_scrot](https://user-images.githubusercontent.com/6799467/33914021-433464a6-dff0-11e7-909f-5fbd505661f5.png)
![2017-12-13-103344_1602x1108_scrot](https://user-images.githubusercontent.com/6799467/33914023-4373c588-dff0-11e7-933d-7e6e4af5cca9.png)
![2017-12-13-103315_1450x880_scrot](https://user-images.githubusercontent.com/6799467/33914025-43b24cf4-dff0-11e7-86a3-b13bca75453a.png)
