### ISSUE TITLE
what packages number exactly is ？

### ISSUE THREAD

**Issue by pengweipro** [dylanaraps/neofetch#867]
why the packages numbers are not the same ？
![_2017-11-13_09-53-23](https://user-images.githubusercontent.com/29443123/32706866-0cff6aa4-c85b-11e7-97ce-834cfd11c228.png)

**Comment by pengweipro** [comment]
I tried 【pacman -Q >>test.txt】,the number is [1975]

**Comment by dylanaraps** [comment]
The package number is the total number of packages from all installed package managers. You've got more than one package manager installed.

**Comment by pengweipro** [comment]
yeah?
i do installed more than one package manager, but the manager "screenfetch" gives the right number!
the question is not how many package manager i got, the question is,
neofetch gave a wrong number!
i guess, maybe the "Enter" of the end line was counted?

**Comment by konimex** [comment]
Neofetch counted *all* package managers you installed. screenfetch only detect it per-OS (this means if you have Arch, *only* pacman would be detected even if you have Nix package manager)

**Comment by pengweipro** [comment]
but should any package manager could output all the packages installed ?
did you mean, the command:
pacman -Q | wc -l
gives the number, which did'nt contain other package manager ?
in your example,
pacman could not detect nix ?

**Comment by konimex** [comment]
`pacman -Q | wc -l` displays the packages that are *only* installed by pacman. That means the number 1975 is correct in pacman. However, because neofetch also detected another package manager in your `PATH`, neofetch calls the package manager in question too to count the packages, and it will be added to your existing package count. (in this case, 1975 + 1 = 1976).

The are some differences between screenfetch and neofetch's method of detecting packages. It isn't as simple as `pacman -Q | wc -l` displaying numbers from another package manager.

In screenfetch, [they only detect packages based on their distro, and it's hardcoded by detecting the distro name](https://gist.github.com/konimex/406c7f47bdfd35784aae10ead5d3ffd4), so if you happen to install Nix/Guix/RPM/emerge (from Gentoo Prefix), screenfetch won't detect it.

Neofetch, however, [takes a different approach](https://gist.github.com/konimex/970aab3945e405e3eaa8ba2522612b07). Instead of hard-coding them per distro name, we decided to count the packages from the package managers installed to accommodate use cases like I mentioned earlier.

For example, if you have 1349 packages installed in pacman, and you have 9 packages installed in Nix package manager which happens to reside in your Arch install, and for some reason you installed `rpm` which has 2 packages for testing builds, screenfetch will only detect `1349`, but neofetch will detect 1349 + 9 + 2 = `1360` instead.

However, if you are adamant that this is not correct and is a bug from neofetch, feel free to send a log here.

**Comment by pengweipro** [comment]
sorry for my ignorance，
and thank you for the explanation，
i thought any package manager should have the ability to get the numbers of package installed together...
