### ISSUE TITLE
Neofetch 3.3.1-git displaying AMD video card device id instead of name

### ISSUE THREAD

**Issue by xanvincent** [dylanaraps/neofetch#870]
## Description
GPU: AMD Device 67df is being displayed instead of AMD RX 580 (or similar). I'm using the git version on elementaryos 0.4.1 Loki (Ubuntu 16.04 LTS). I think this is due to what is being output by lspci but I'm not sure? Is this a bug or configuration problem?

#### Neofetch version
`sean@zinc:~/git/neofetch$ ./neofetch --version`
`Neofetch 3.3.1-git`

## Screenshot
[here](https://imgur.com/a/cAuJt)

## Config file
None.

## Verbose log
[dpaste link](http://dpaste.com/0FK2K4C)

**Comment by konimex** [comment]
This may occur because your `pci-ids` file is not up-to-date.

If your vendor ID of your GPU (check it with `lspci -nn`) is `1002`, then [your device should've been detected by the pci-ids repo](https://pci-ids.ucw.cz/read/PC/1002/67df).

See [this](https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linuxfreebsd-why-does-getgpu-doesnt-show-my-exact-video-card-name) for more information.

Since this is not a neofetch bug, I'm closing this one.
