### ISSUE TITLE
Is there padding/align option?

### ISSUE THREAD

**Issue by lapsio** [dylanaraps/neofetch#895]
## Description

I'm not sure if there already is such option - but is there a way to align results? I tried to just insert spaces in categories names but they seem to be trimmed as only one space after name remains displayed. It'd make much more sense to align results for barinfo display mode as currently it looks really messy and kind of defeats purpose of displaying bars if they don't look clean at all...

**Comment by Snuggle** [comment]
This kind of already exists, it's a hacky fix though. I had to search through Neofetch's source code. I used it to align my rainbow, since my terminal supports 16-million truecolor and I like showing it off.

Basically you just need to add `printf '\e[%bC%b' "$text_padding" "${zws}${cols}"` for aligning things.

![image](https://user-images.githubusercontent.com/26250962/45259232-9a151b00-b3bf-11e8-90ee-0a4695185802.png)
![image](https://user-images.githubusercontent.com/26250962/45259254-0f80eb80-b3c0-11e8-894f-de1cd19900d3.png)


^ Here is my config for the above. 
(Requires kitty terminal for native image support - https://github.com/kovidgoyal/kitty)
https://pastebin.com/C4LbSySJ

**Comment by joelostblom** [comment]
Another workaround is to pipe the output through `column`:

```bash
neofetch --stdout | column -t -s ':'
```

gives

```
OS                  Ubuntu 18.04.2 LTS x86_64                    
Kernel              4.15.0-45-generic                               
Uptime              2d 4h 48m                                              
Packages            1823                                                   
Shell               zsh 5.4.2   
...
```

**Comment by jackcogdill** [comment]
Another workaround is using `--separator '\t'`

**Comment by svenknoke** [comment]
if you want color output with the piping through `column` trick you can use:
`neofetch --off --color_blocks off | column -t -s ':'`

**Comment by dylanaraps** [comment]
Closing as stale.

**Comment by hikkidev** [comment]
A cringe-way workaround
```bash
neofetch --ascii_distro arch_small --color_blocks off | column -ts ":" -o "" && neofetch --off --disable $(cat .config/neofetch/config.conf | grep -oP "(?<=info )\w+|(?<=.\" )\w+" | sed -e "/^cols$/d" | tr "\n" " ") | tail -n +2
```

**Comment by wave864** [comment]
Here's a simple workaround: while normal spaces at the end of the "subtitle" get stripped, I found that [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) can be used to align the information manually in the config file.

Much easier to read at a glance in my opinion.

![Screenshot](https://github.com/dylanaraps/neofetch/assets/53859987/6defb20c-9167-4ab9-9386-fbcb9b97e293)

**Comment by its-19818942118** [comment]
another way is just using \n for space in this way you can align it

**Comment by its-19818942118** [comment]
Another simple wayaround is using `\n` it outputs as space you add many more to center it as you like or align
