### ISSUE TITLE
Unexpected backslash being inserted into title variable upon Neofetch launch

### ISSUE THREAD

**Issue by KamranMackey** [dylanaraps/neofetch#933]
## Description
For some reason, a backslash is being inserted into the title variable, so the title shows up as `kamran\@Aurora` instead of `kamran@Aurora`. I know my username doesn't have a backslash in it, so that's not an issue. I have no idea why this is being caused. The issue happens in both Apple Terminal, and iTerm 2. My config file, and the verbose log, are attached below as a gist link.

#### Neofetch version
`3.3.1-git` (Homebrewed)

## Screenshot
![screen shot 2018-03-24 at 4 28 16 pm](https://user-images.githubusercontent.com/1617100/37869661-368b68ae-2f81-11e8-899a-15c2809a8f09.png)

## Config file & verbose log
[Gist link](https://gist.github.com/KamranMackey/bd90826e1517feff2ecde700559d948c)

**Comment by dylanaraps** [comment]
It looks to me like this is an issue with your color settings. Does this occur with `--config off`?

**Comment by dylanaraps** [comment]
What's the output of these commands?:

```sh
echo "$USER"
whoami
echo "${HOME##*/}"
echo "$HOSTNAME"
hostname
```

**Comment by KamranMackey** [comment]
It happened even with Apple Terminal, and I didn't change any configuration settings for neofetch or my color settings aside from adding the "weather" command and uncommenting a few things for the base config. Also the color settings in iTerm at the time were left at defaults too. I'll run those commands later though when I get the chance. At the moment I'm booted into Windows.

**Comment by KamranMackey** [comment]
No longer on macOS due to my hard drive corrupting, so until I get macOS reinstalled, I can't test this. Closing for now, will re-open once I find the time to get macOS re-installed.

**Comment by iandrewt** [comment]
I'm able to reproduce this issue, ill see if I can figure out when it started

**Comment by konimex** [comment]
Because this is confirmed bug, I'm reopening this issue.

**Comment by iandrewt** [comment]
The relevant lines haven't been edited since 2016. Any idea on how to actually diagnose this?

**Comment by konimex** [comment]
It can be the coloring part that triggers the extra backslash, like ${title_color}, ${bold}, or maybe ${at_color}.

**Comment by iandrewt** [comment]
Yeah that worked for me. The `@` symbol lost its colour and bold from doing that too. 
![screen shot 2018-04-08 at 4 28 26 pm](https://user-images.githubusercontent.com/12795256/38464026-f453b96c-3b49-11e8-860b-ac7e2bdf6ec6.png)

**Comment by konimex** [comment]
I think that was intended since the output for Mac is the same in my testing (granted, it is a Linux system but since we're using bash it should have a similar output apart from fonts or colorscheme)

![2018-04-08-133254_804x604_scrot](https://user-images.githubusercontent.com/15692230/38464065-b231a6be-3af6-11e8-9091-8475137cdbd0.png)

**Comment by iandrewt** [comment]
Do you get the backslash when using `\\e`?

**Comment by konimex** [comment]
Not in Linux, but I tested it somewhere else and found out this bug is also happening in an AIX server and my Solaris VBox.
![2018-04-08-133900_858x1018_scrot](https://user-images.githubusercontent.com/15692230/38464109-91b9f746-3af7-11e8-827c-a6402e9640f5.png)
![2018-04-08-134257_1054x826_scrot](https://user-images.githubusercontent.com/15692230/38464154-1ade874e-3af8-11e8-80e0-811d044e1bec.png)

This may also happen in BSDs, I'll edit this post later if I found out it does happen there too.

**Comment by iandrewt** [comment]
It's an issue with bash 3.2, if bash is installed from homebrew (4.4) the issue doesn't occur

**Comment by konimex** [comment]
Fixed. Please reopen this issue if the issue still exists on master.
