### ISSUE TITLE
RAM usage not factoring in swap on Oracle Solaris

### ISSUE THREAD

**Issue by iandrewt** [dylanaraps/neofetch#969]
## Description

RAM usage is showing as `Memory: -45805MiB / 8192MiB`

My uni's UNIX server has a huge swap file (above 30GB I think) and 8GB of physical RAM, but neofetch is only looking at the physical RAM for the total RAM. Haven't looked into how to fix this, but the 8192 is coming directly from `prtconf` which only shows the physical RAM

#### Neofetch version

master

**Comment by dylanaraps** [comment]
This is intended is it not? Every OS works this way currently.

**Comment by konimex** [comment]
I knew this would be brought up eventually.

Calculating RAM usages and totals in Solaris is a bit ~~weird~~unique since I'm not even sure if `vmstat` gives the accurate output in a system without swap.

For the totals, physical memory should be accurate, but for swap, what is the output of `swap -l` or `swap -s`?

**Comment by iandrewt** [comment]
```bash
Last login: Fri May  4 17:17:02 2018 from 10.12.20.65
$ swap -l                                                                                   
swapfile             dev  swaplo blocks   free
/dev/swap           4294967295,4294967295     16 33554432 31322240
$ swap -s
total: 1116376k bytes allocated + 0k reserved = 1116376k used, 15660840k available
$ 
```

**Comment by konimex** [comment]
If `swap -l` is accurate, then considering `33554432` is a 512-byte block value. The swap size would be `33554432 * 512/1024` = 16384 MB = 16 GB. But looking at your free value, seems unlikely.

I would expect the command to not work since it needs root, but what about the command `echo ::mem | mdb -k` ?

**Comment by iandrewt** [comment]
$ echo ::mem | mdb -k
mdb: failed to open /dev/ksyms: No such file or directory

**Comment by konimex** [comment]
I don't know if this will work, but try to use this perl script:

https://github.com/justintime/nagios-plugins/blob/master/check_mem/check_mem.pl

Does it work with regular Solaris? If not, try to change line 211 from joyent to SunOS.

**Comment by iandrewt** [comment]
Doesn't run at all, always prints the usage info no matter what I try, with no error

**Comment by konimex** [comment]
@iandrewt, if you still have access to the Solaris machine, please run `pagesize`, `kstat -p unix:0:system_pages:pagestotal` and `kstat -p unix:0:system_pages:pagesfree` respectively and put the output back here.

**Comment by iandrewt** [comment]
```bash
$ pagesize
8192
$ kstat -p unix:0:system_pages:pagestotal
unix:0:system_pages:pagestotal  8130178
$ kstat -p unix:0:system_pages:pagesfree
unix:0:system_pages:pagesfree   6765885
```

**Comment by konimex** [comment]
Alright. Pushed https://github.com/dylanaraps/neofetch/commit/0168516a2c00b115b7b0ace7e36ac7f2da6ece7e, is it accurate now (or at least close enough)?

**Comment by iandrewt** [comment]
Yeah seems to be correct now :+1:
